---
title: "Introdução a probabilidade"
output: html_notebook
---

## Slide03
  - Exemplo 01

```{r}

Idade <- 12:20
frequencia_absoluta <- c(2,0,0,3,0,1,4,1,1)
barplot(frequencia_absoluta, names=Idade, xlab = "Idade em anos",
        ylab = "Frequência absoluta", main = "Gráfico da variável Idade",
        ylim = range(0,5), col="purple")

```

   - Exemplo 02

```{r}
frequencia_relativa <- c(0.3056, 0.3333, 0.3611)
names(frequencia_relativa) <- c("Capital","Interior","Outra" )

pie(frequencia_relativa, main = "Grafico para a variàvel Região de Procedência",
    labels = c("30,56%", "33,33%", "36,11%"), col = c(15,4,3))
legend(1,1,fill = c(15,4,3), legend = c("Capital", "Interior", "Outra"), box.col=NA)
```

  - Exercicio 01
  
```{r}

frequencia_refri <- c(0.4318, 0.2955, 0.1818, 0.0909 )
pie(frequencia_refri, main = "Gráfico para a variável Refrigerante", 
    labels = c("43,18%", "29,55%", "18,18%", "9,09%"), col = c(22,18,15,11))
legend(1,1,fill = c(22,18,15,11), legend = c("Coca-cola", "Pepsi", "Coca-cola light", "Sprite"), box.col=NA)
```

  Exercicio 02
    - a
```{r}

estado <- c("Solteiro", "Casado")
frequencia_estado <- c(16, 20)

barplot(frequencia_estado, names = estado, xlab = "Estado Civil",
        ylab = "Frequência estado civil", main = "Gráfico para variável estado civil",
        ylim = range(0,20), col = "blue")
```

  Exercicio 02
    - b
    
```{r}
frequencia_filhos <- c(0.4444, 0.1111, 0.1389, 0.1944, 0.0833, 0.0278)

pie(frequencia_filhos, main = "Gráfico para variável número de filhos", 
    labels = c("44,44%", "11,11%", "13,89%", "19,44%", "8,33%", "2,78%"),
    col = c(2,3,4,5,6,7))
legend(1,1, fill = c(2,3,4,5,6,7), legend = c("não informado","nenhum filho", "1 filho", "2 filhos", "3 filhos", "5 filhos"), box.col = NA)

```